### Modificar Vehículo
POST http://localhost:5000/api/modificar_vehiculo
Content-Type: application/json

{
    "nombreMarca": "Toyota",
    "modelo": "Corolla",
    "estilo": "Sedan",
    "año": 2020,
    "transmision": "Manual",
    "estado": 1,
    "color": "Rojo",
    "combustible": "Gasolina",
    "cilindrada": 4,
    "numeroPasajeros": 5,
    "numeroPuertas": 4,
    "placaNoCambia": "262624"
}


### Eliminar Vehículo
POST http://localhost:5000/api/vehiculos/eliminar
Content-Type: application/json

{
    "placa": "MTG789"
}

### Agregar Vehículo



POST http://localhost:5000/api/vehiculos/insertar
Content-Type: application/json

{
    "marca": "Hyundai",
    "modelo": "Tucson",
    "estilo": "SUV",
    "anio": 2016,
    "trans": "Tiptronic",
    "estado": 1,
    "color": "Azul",
    "combustible": "Gasolina",
    "cilindrada": 4,
    "pasajeros": 5,
    "puertas": 5,
    "placa": "BJX871"
}

### Modificar Repuesto
POST http://localhost:5000/api/repuestos/modificar
Content-Type: application/json

{
    "codigo": 1,
    "nombre": "Tijereta delantera derecha",
    "marca": "Toyota",
    "modelo": "4Runner",
    "cantidad": 1,
    "anio": 1985
}

### Eliminar Repuesto
POST http://localhost:5000/api/repuestos/eliminar
Content-Type: application/json

{
    "codigo": 4
}

### Modificar Cliente
POST http://localhost:5000/api/clientes/modificar
Content-Type: application/json

{
    "idCliente": 1,
    "nombre": "Juan",
    "correo": "juan@gmail.com",
    "direccion": "Guanacaste"
}

### Eliminar Cliente
POST http://localhost:5000/api/clientes/eliminar
Content-Type: application/json

{
    "idCliente": 2
}

### Agregar Cliente
POST http://localhost:5000/api/clientes/insertar
Content-Type: application/json

{
    "nombre": "Maria",
    "correo": "maria@gmail.com",
    "direccion": "San Jose"
}